# Generated by Django 3.1.6 on 2021-02-17 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('innapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='descriptions',
            new_name='description',
        ),
    ]
