# Generated by Django 3.1.6 on 2021-02-25 14:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('innapp', '0002_auto_20210217_1450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='date',
        ),
        migrations.AddField(
            model_name='course',
            name='endDate',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='slutt dato'),
        ),
        migrations.AddField(
            model_name='course',
            name='restriction',
            field=models.IntegerField(default=0, verbose_name='spor'),
        ),
        migrations.AddField(
            model_name='course',
            name='startDate',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='start dato'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(verbose_name='beskrivelse'),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=120, verbose_name='tiltak'),
        ),
    ]
