# Generated by Django 3.1.7 on 2021-04-08 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('innapp', '0003_auto_20210225_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(default='', max_length=100, verbose_name='kategori'),
        ),
    ]
