# Generated by Django 3.1.6 on 2021-03-23 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('innapp', '0003_auto_20210225_1524'),
        ('userpreferences', '0003_auto_20210323_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='userperference',
            name='selected',
            field=models.ManyToManyField(to='innapp.Course'),
        ),
    ]
