# Generated by Django 3.1.6 on 2021-03-23 15:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userpreferences', '0004_userperference_selected'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userperference',
            name='user',
        ),
        migrations.AddField(
            model_name='userperference',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
