# Generated by Django 3.1.6 on 2021-03-23 15:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userpreferences', '0005_auto_20210323_1515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userperference',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='userperference',
            name='selected_courses',
        ),
        migrations.AddField(
            model_name='userperference',
            name='user',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
